---
- hosts: all
  tags: [macos]
  tasks:
  - name: add Homebrew taps
    homebrew_tap: name={{item}}
    with_items:
    - neovim/neovim

  - name: install Homebrew packages
    homebrew:
      name: "{{item.name}}"
      install_options: "{{item.install_options}}"
      state: latest
      update_homebrew: yes
    with_items:
    - {name: ack, install_options: ''}
    - {name: ag, install_options: ''}
    - {name: awscli, install_options: ''}
    - {name: chruby, install_options: ''}
    - {name: coreutils, install_options: ''}
    - {name: ctags, install_options: ''}
    - {name: direnv, install_options: ''}
    - {name: docker, install_options: ''}
    - {name: docker-machine, install_options: ''}
    - {name: elixir, install_options: ''}
    - {name: elm, install_options: ''}
    - {name: fasd, install_options: ''}
    - {name: fd, install_options: ''}
    - {name: fzf, install_options: ''}
    - {name: git, install_options: ''}
    - {name: go, install_options: ''}
    - {name: gpg, install_options: ''}
    - {name: htop, install_options: ''}
    - {name: jq, install_options: ''}
    - {name: jsonpp, install_options: ''}
    - {name: kube-ps1, install_options: ''}
    - {name: kubectx, install_options: ''}
    - {name: libgit2, install_options: ''}
    - {name: memcached, install_options: ''}
    - {name: neovim, install_options: ''}
    - {name: pinentry-mac, install_options: ''}
    - {name: postgresql, install_options: ''}
    - {name: pstree, install_options: ''}
    - {name: python@2, install_options: ''}
    - {name: python3, install_options: ''}
    - {name: reattach-to-user-namespace, install_options: ''}
    - {name: ripgrep, install_options: ''}
    - {name: ruby-install, install_options: ''}
    - {name: shellcheck, install_options: ''}
    - {name: ssh-copy-id, install_options: ''}
    - {name: tig, install_options: ''}
    - {name: tmate, install_options: ''}
    - {name: tmux, install_options: ''}
    - {name: tree, install_options: ''}
    - {name: vim, install_options: ''}
    - {name: watch, install_options: ''}
    - {name: wget, install_options: ''}
    - {name: yarn, install_options: ''}
    - {name: zsh, install_options: ''}

  - name: install Homebrew casks
    homebrew_cask: name={{item}} install_options=appdir=/Applications
    with_items:
    - docker
    - flycut
    - iterm2
    - shiftit
