---
- hosts: all
  tags: [ubuntu]
  tasks:
  - name: add apt repositories
    become: yes
    become_method: sudo
    apt_repository: repo={{ item }}
    with_items:
    - ppa:git-core/ppa
    - ppa:neovim-ppa/{{ [ansible_distribution_release] | issubset(['xenial', 'yakkety']) | ternary('stable', 'unstable') }}
    - ppa:pi-rho/dev
    - ppa:tmate.io/archive
    - ppa:aacebedo/fasd
    - ppa:noobslab/themes
    - ppa:noobslab/icons

  - name: add VirtualBox repository
    become: yes
    become_method: sudo
    lineinfile: dest=/etc/apt/sources.list.d/virtualbox.list line="deb http://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib" create=yes

  - name: add VirtualBox repository key
    become: yes
    become_method: sudo
    apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc

  - name: install requirements
    become: yes
    become_method: sudo
    apt: name={{item}} state=latest
    with_items:
    - aptitude
    - apt-transport-https

  - name: upgrade packages
    become: yes
    become_method: sudo
    apt:
      update_cache: yes
      upgrade: yes

  - name: install apt packages
    become: yes
    become_method: sudo
    apt: name={{ item }} state=latest
    with_items:
    - ack-grep
    - build-essential
    - cmake
    - curl
    - direnv
    - docker.io
    - elixir
    - exuberant-ctags
    - fasd
    - git
    - hfsprogs
    - htop
    - jq
    - kubeadm
    - kubectl
    - kubelet
    - kubernetes-cni
    - libcurl4-openssl-dev
    - libevent-dev
    - libncurses5-dev
    - libssl-dev
    - libxml2
    - libxml2-dev
    - mercurial
    - neovim
    - nodejs
    - openssl
    - pinentry-curses
    - pkg-config
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - python3.6
    - ruby
    - shellcheck
    - silversearcher-ag
    - tig
    - tmate
    - tmux-next
    - tree
    - vim
    - vim-nox
    - virtualbox-5.1
    - wget
    - zsh

  - name: install Vagrant
    become: yes
    become_method: sudo
    apt:
      deb: https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.deb

  - name: download godeb
    get_url: url=https://godeb.s3.amazonaws.com/godeb-amd64.tar.gz dest=/tmp/

  - name: install godeb
    unarchive: src=/tmp/godeb-amd64.tar.gz dest={{ ansible_env.HOME }}/.local/bin

  - name: install go
    command: godeb install
    ignore_errors: yes

  - name: set zsh as default
    become: yes
    become_method: sudo
    user:
      name: "{{ansible_env.USER }}"
      append: yes
      groups:
      - docker

- hosts: all
  tags: [ubuntu_x]
  tasks:
  - name: install apt X packages
    become: yes
    become_method: sudo
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
    - gnome
    - gnome-tweak-tool
    - flatabulous-theme
    - fonts-inconsolata
    - ultra-flat-icons
    - clipit
    - xclip
    - xsel
