---
- hosts: all
  tags: [ubuntu, gentoo, macos]
  tasks:
  - name: install go apps
    command: go install {{ item }}
    with_items:
    - github.com/vektra/mockery/...@latest
    - gotest.tools/gotestsum@latest
