---
- hosts: all
  tags: [ubuntu, gentoo, macos]
  tasks:
  - name: install go apps
    command: go get {{ item }}
    with_items:
    - github.com/git-duet/git-duet/...
    - github.com/vektra/mockery/.../
    - gotest.tools/gotestsum
