---
- hosts: all
  tags: [ubuntu, gentoo, macos]
  tasks:
  - name: clone vim config
    git:
      repo: https://github.com/luan/nvim
      dest: ~/.config/nvim

  - name: create config/nvim folder
    file:
      path: ~/.config/nvim/lua/user
      state: directory

  - name: install neovim pip package
    pip: name=pynvim state=latest extra_args=--user executable=pip3

  - name: set up symlinks
    file:
      path: "{{item.target}}"
      src: "{{item.src}}"
      state: link
      force: yes
    with_items:
    - {target: ~/.config/nvim/lua/user/after.lua, src: "{{ansible_env.PWD}}/../config/nvim/after.lua"}
    - {target: ~/.config/nvim/lua/user/before.lua, src: "{{ansible_env.PWD}}/../config/nvim/before.lua"}
    - {target: ~/.config/nvim/lua/user/plugins.lua, src: "{{ansible_env.PWD}}/../config/nvim/plugins.lua"}
