---
- hosts: all
  tags: [ubuntu]
  tasks:
  - name: add apt repositories
    become: yes
    become_method: sudo
    apt_repository: repo={{ item }}
    with_items:
    - ppa:mmstick76/alacritty
    - ppa:daniruiz/flat-remix

  - name: install gui packages
    become: yes
    become_method: sudo
    apt:
      state: latest
      name:
      - alacritty
      - chrome-gnome-shell
      - flat-remix-gnome
      - fonts-inconsolata
      - flat-remix
      - flat-remix-gtk
      - gnome
      - gnome-tweak-tool
      - imagemagick
      - libglib2.0-dev-bin
      - ultra-flat-icons

  - name: Install Zoom
    become: true
    become_method: sudo
    apt:
      deb: https://zoom.us/client/latest/zoom_amd64.deb

  - name: Install Mullvad
    become: true
    become_method: sudo
    apt:
      deb: https://mullvad.net/download/app/deb/latest/

  - name: Install Slack
    become: true
    become_method: sudo
    apt:
      deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.12.2-amd64.deb

  - name: install autorandr
    pip: name=autorandr state=latest extra_args=--user executable=pip3
