---
- hosts: all
  tags: [ubuntu]
  tasks:
  - name: add apt repositories
    become: yes
    become_method: sudo
    apt_repository: repo={{ item }}
    with_items:
    - ppa:daniruiz/flat-remix
    - ppa:papirus/papirus

  - name: Install Alacritty
    become: yes
    become_method: sudo
    community.general.snap:
      name: alacritty
      classic: true

  - name: install gui packages
    become: yes
    become_method: sudo
    apt:
      state: latest
      name:
      - arc-theme
      - chrome-gnome-shell
      - flat-remix
      - flat-remix-gnome
      - flat-remix-gtk
      - fonts-inconsolata
      - gnome
      - gnome-shell-extension-manager
      - gnome-tweaks
      - imagemagick
      - libglib2.0-dev-bin
      - numix-gtk-theme
      - papirus-icon-theme

  - name: Install Zoom
    become: true
    become_method: sudo
    apt:
      deb: https://zoom.us/client/latest/zoom_amd64.deb

  - name: Install Mullvad
    become: true
    become_method: sudo
    apt:
      deb: https://mullvad.net/download/app/deb/latest/

  - name: Install Slack
    become: true
    become_method: sudo
    apt:
      deb: https://downloads.slack-edge.com/releases/linux/4.26.1/prod/x64/slack-desktop-4.26.1-amd64.deb

  - name: install autorandr
    pip: name=autorandr state=latest extra_args=--user executable=pip3
